variables:
    APPNAME: nugetLib
    
before_script:
  - nuget restore %APPNAME%

stages:
    - build
    - installer

jobBuildAssembly:
    stage: build
    script:
        - MSBuild.exe /maxcpucount /nologo /p:Configuration=Release /p:DocumentationFile=%APPNAME%.xml "%APPNAME%/%APPNAME%.sln"
    artifacts:
        paths:
            - '%APPNAME%\%APPNAME%\bin\Release'
    tags:
        - msbuild

jobCreateWinInstaller:
    stage: installer
    tags:
        - msbuild
        - wix
    script:
        - MSBuild.exe /maxcpucount /nologo /p:Configuration=Installer /p:DocumentationFile=%APPNAME%.xml "%APPNAME%/%APPNAME%.sln"
        - xcopy /s /y /i %APPNAME%\%APPNAME%Setup\bin\Release .\
    artifacts:
        paths:
            - .\*.msi


