variables:
    APPNAME: nugetLib
    NUGET_PATH: \\VM-SRV-APP03\SoftwareLibrary\Software\NuGetLib
    
before_script:
  - nuget restore %APPNAME%

stages:
    - build
    - installer
    - deploy

jobBuildAssembly:
    stage: build
    script:
        - MSBuild.exe /maxcpucount /nologo /p:Configuration=Release /p:DocumentationFile=%APPNAME%.xml "%APPNAME%/%APPNAME%.sln"
    artifacts:
        paths:
            - '%APPNAME%\%APPNAME%\bin\Release'
    tags:
        - msbuild

jobCreateWinInstaller:
    stage: installer
    tags:
        - msbuild
        - wix
    script:
        - MSBuild.exe /maxcpucount /nologo /p:DocumentationFile=%APPNAME%.xml "%APPNAME%/%APPNAME%.sln"
        - xcopy /s /y /i %APPNAME%\%APPNAME%Installer\bin\Release\*.msi .\
    artifacts:
        paths:
            - .\*.msi

jobDeployMsi:
    stage: deploy
    only:
        - tags
    tags:
        - msbuild
    script:
        - xcopy /s /y /i .\*.msi %NUGET_PATH%

